"""empty message

Revision ID: 17aaf464d0e8
Revises: b4a35f673d9c
Create Date: 2022-08-02 21:39:24.275855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17aaf464d0e8'
down_revision = 'b4a35f673d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'developers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'developers', type_='foreignkey')
    op.drop_column('developers', 'user_id')
    # ### end Alembic commands ###
