"""empty message

Revision ID: fda7cdbeb22d
Revises: 6b29f08f6c43
Create Date: 2022-08-03 19:41:14.923337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda7cdbeb22d'
down_revision = '6b29f08f6c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developers', 'months_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developers', 'months_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
