#Projeto Python #1 Inspiração
nome = input('Olá, antes de qualquer coisa, preciso de seu nome apenas, qualquer um que você se sinta confortável. : ')
nome2 = nome.split()
print(f'Certo, prazer {nome2} ! Este aqui é o meu pequeno projeto chamado "Inspiração". \n "Inspiração" tem como foco, desenvolver qualquer habilidade que você acha que não possui ou acredita que não tenha.')
print('Por mais desanimador que seja a vida, não pense apenas dessa forma. Tente imaginar o que mais você poderia fazer com ela e o que ela te traz de ruim e bom.')
print('Tente se lembrar daquele momento inspirador, de quando você era criança e viu seu super-herói na TV, mesmo que não tenha visto, apenas foque em buscar alguma energia positiva que você sente saudade.', end="\n") 
print('Certo, se você não conseguiu, uma dica, saia do seu computador ou seja lá aonde você estiver vendo isso, vá para algum lugar com uma vista de algum lugar, não importa a vista, \n desde que seja algo que distraia você. E volta daqui alguns minutos.', end='\n')
print('Bom, agora que você voltou/conseguiu a energia positiva, vamos começar. Responda algumas perguntas apenas com *SIM* ou *NÃO* .')
item1 = input('Essa energia positiva, era de uma memoria recente?: ')
item2 = input('Te deixou com medo em alguma hora?: ')
item3 = input('Você gostaria de esquecer essa memoria?: ')
item4 = input('Se você pudesse "reviver" essa memoria, você faria? : ')
item5 = input('Essa memoria te fez refletir em algum momento a ponto de você esquecer deste questionario ?: ')
item6 = input('Isto te inspirou em algum momento?: ')
item7 = input('Você está se sentindo sozinho?: ')
